/*
 * Footprint Chess: ids of recorded voice clips, per language.
 *
 * Lists only the ids that have a matching file at
 * audio/voice/<lang>/<id>.mp3, so js/voice.js never fetches a file that
 * does not exist (a 404 request would still cost a network round trip, and
 * the device may be offline). Every id here must also be a key in
 * FC.lessons.LINES, and every language key must be one of
 * FC.lessons.LANGS (tests/lessons.test.js checks all of this). For an id
 * missing here, js/voice.js falls back to speechSynthesis, or to silence
 * with correct pacing.
 *
 * Generated by tools/make-voice.js (run with --index-only to rebuild this
 * file from whatever is already in audio/voice/ without contacting Azure),
 * or edited by hand after adding a file yourself.
 *
 * Classic script: exposes window.FC.voiceClips in the browser and
 * module.exports in Node.
 */
(function (root) {
  'use strict';

  var voiceClips = {
    en: [
      "bishop-1",
      "bishop-2",
      "bishop-3",
      "capture-1",
      "capture-2",
      "capture-3",
      "great",
      "hello-1",
      "hello-2",
      "hello-3",
      "hint-pawn",
      "king-1",
      "king-2",
      "king-3",
      "knight-1",
      "knight-2",
      "knight-3",
      "meet-b",
      "meet-k",
      "meet-n",
      "meet-p",
      "meet-q",
      "meet-r",
      "mission",
      "next",
      "pawn-1",
      "pawn-2",
      "pawn-3",
      "pawncap-1",
      "pawncap-2",
      "pick",
      "queen-1",
      "queen-2",
      "queen-3",
      "rook-1",
      "rook-2",
      "rook-3",
      "tap-footprint",
      "tap-piece",
      "won",
      "your-turn"
    ],
    te: [
      "bishop-1",
      "bishop-2",
      "bishop-3",
      "capture-1",
      "capture-2",
      "capture-3",
      "great",
      "hello-1",
      "hello-2",
      "hello-3",
      "hint-pawn",
      "king-1",
      "king-2",
      "king-3",
      "knight-1",
      "knight-2",
      "knight-3",
      "meet-b",
      "meet-k",
      "meet-n",
      "meet-p",
      "meet-q",
      "meet-r",
      "mission",
      "next",
      "pawn-1",
      "pawn-2",
      "pawn-3",
      "pawncap-1",
      "pawncap-2",
      "pick",
      "queen-1",
      "queen-2",
      "queen-3",
      "rook-1",
      "rook-2",
      "rook-3",
      "tap-footprint",
      "tap-piece",
      "won",
      "your-turn"
    ]
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = voiceClips;
  } else {
    root.FC = root.FC || {};
    root.FC.voiceClips = voiceClips;
  }
})(this);
