/*
 * Footprint Chess: ids of recorded voice clips, per language.
 *
 * Lists only the ids that have a matching file at
 * audio/voice/<lang>/<id>.mp3, so js/voice.js never fetches a file that
 * does not exist (a 404 request would still cost a network round trip, and
 * the device may be offline). Every id here must also be a key in
 * FC.lessons.LINES, and every language key must be one of
 * FC.lessons.LANGS (tests/lessons.test.js checks all of this). Starts
 * empty: until recordings are added, js/voice.js falls back to
 * speechSynthesis, or to silence with correct pacing.
 *
 * Generated by tools/make-voice.js (run with --index-only to rebuild this
 * file from whatever is already in audio/voice/ without contacting Azure),
 * or edited by hand after adding a file yourself.
 *
 * Classic script: exposes window.FC.voiceClips in the browser and
 * module.exports in Node.
 */
(function (root) {
  'use strict';

  var voiceClips = {
    en: [],
    te: []
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = voiceClips;
  } else {
    root.FC = root.FC || {};
    root.FC.voiceClips = voiceClips;
  }
})(this);
