/*
 * Footprint Chess: offline mode (stage 7).
 *
 * A service worker that keeps every file of the app in one cache per
 * version, so after the first visit the app opens and plays with no
 * internet. It stores app files only, never anything about the child
 * (progress stays in local storage, see PRIVACY.md), and it only ever
 * answers requests for this site's own files.
 *
 * Install: fetch every file into a new cache (skipping the browser's HTTP
 * cache, so a new version never keeps an old file). Activate: delete older
 * caches and take over at once, so a tablet that keeps one tab open for
 * weeks still updates on its next page load. Fetch: this site's GET
 * requests come from the cache (the address's ?lang= and ?theme= are
 * ignored when matching), else from the network; a page asked for while
 * offline and not cached gets index.html.
 *
 * The file list and version below are written by tools/make-offline.js;
 * run it after changing any page, style, script or clip.
 *
 * Classic worker script, ES2017, no imports.
 */
'use strict';

// BEGIN GENERATED by tools/make-offline.js (do not edit by hand)
var VERSION = '9af7bbdee43c';
var FILES = [
  './',
  'index.html',
  'help.html',
  'check.html',
  'css/app.css',
  'css/check.css',
  'css/help.css',
  'js/app.js',
  'js/army.js',
  'js/board.js',
  'js/book-ui.js',
  'js/check.js',
  'js/game-list.js',
  'js/games-ui.js',
  'js/games.js',
  'js/grownups-ui.js',
  'js/hands.js',
  'js/langs.js',
  'js/lessons.js',
  'js/levels.js',
  'js/player.js',
  'js/pond.js',
  'js/profile-ui.js',
  'js/quiz.js',
  'js/rules.js',
  'js/sound.js',
  'js/stickers.js',
  'js/store.js',
  'js/themes.js',
  'js/voice-clips.js',
  'js/voice.js',
  'audio/voice/en/bishop-1.mp3',
  'audio/voice/en/bishop-2.mp3',
  'audio/voice/en/bishop-3.mp3',
  'audio/voice/en/capture-1.mp3',
  'audio/voice/en/capture-2.mp3',
  'audio/voice/en/capture-3.mp3',
  'audio/voice/en/great.mp3',
  'audio/voice/en/hello-1.mp3',
  'audio/voice/en/hello-2.mp3',
  'audio/voice/en/hello-3.mp3',
  'audio/voice/en/hint-pawn.mp3',
  'audio/voice/en/king-1.mp3',
  'audio/voice/en/king-2.mp3',
  'audio/voice/en/king-3.mp3',
  'audio/voice/en/knight-1.mp3',
  'audio/voice/en/knight-2.mp3',
  'audio/voice/en/knight-3.mp3',
  'audio/voice/en/meet-b.mp3',
  'audio/voice/en/meet-k.mp3',
  'audio/voice/en/meet-n.mp3',
  'audio/voice/en/meet-p.mp3',
  'audio/voice/en/meet-q.mp3',
  'audio/voice/en/meet-r.mp3',
  'audio/voice/en/mission.mp3',
  'audio/voice/en/next.mp3',
  'audio/voice/en/pawn-1.mp3',
  'audio/voice/en/pawn-2.mp3',
  'audio/voice/en/pawn-3.mp3',
  'audio/voice/en/pawncap-1.mp3',
  'audio/voice/en/pawncap-2.mp3',
  'audio/voice/en/pick.mp3',
  'audio/voice/en/queen-1.mp3',
  'audio/voice/en/queen-2.mp3',
  'audio/voice/en/queen-3.mp3',
  'audio/voice/en/rook-1.mp3',
  'audio/voice/en/rook-2.mp3',
  'audio/voice/en/rook-3.mp3',
  'audio/voice/en/tap-footprint.mp3',
  'audio/voice/en/tap-piece.mp3',
  'audio/voice/en/won.mp3',
  'audio/voice/en/your-turn.mp3',
  'audio/voice/te/bishop-1.mp3',
  'audio/voice/te/bishop-2.mp3',
  'audio/voice/te/bishop-3.mp3',
  'audio/voice/te/capture-1.mp3',
  'audio/voice/te/capture-2.mp3',
  'audio/voice/te/capture-3.mp3',
  'audio/voice/te/great.mp3',
  'audio/voice/te/hello-1.mp3',
  'audio/voice/te/hello-2.mp3',
  'audio/voice/te/hello-3.mp3',
  'audio/voice/te/hint-pawn.mp3',
  'audio/voice/te/king-1.mp3',
  'audio/voice/te/king-2.mp3',
  'audio/voice/te/king-3.mp3',
  'audio/voice/te/knight-1.mp3',
  'audio/voice/te/knight-2.mp3',
  'audio/voice/te/knight-3.mp3',
  'audio/voice/te/meet-b.mp3',
  'audio/voice/te/meet-k.mp3',
  'audio/voice/te/meet-n.mp3',
  'audio/voice/te/meet-p.mp3',
  'audio/voice/te/meet-q.mp3',
  'audio/voice/te/meet-r.mp3',
  'audio/voice/te/mission.mp3',
  'audio/voice/te/next.mp3',
  'audio/voice/te/pawn-1.mp3',
  'audio/voice/te/pawn-2.mp3',
  'audio/voice/te/pawn-3.mp3',
  'audio/voice/te/pawncap-1.mp3',
  'audio/voice/te/pawncap-2.mp3',
  'audio/voice/te/pick.mp3',
  'audio/voice/te/queen-1.mp3',
  'audio/voice/te/queen-2.mp3',
  'audio/voice/te/queen-3.mp3',
  'audio/voice/te/rook-1.mp3',
  'audio/voice/te/rook-2.mp3',
  'audio/voice/te/rook-3.mp3',
  'audio/voice/te/tap-footprint.mp3',
  'audio/voice/te/tap-piece.mp3',
  'audio/voice/te/won.mp3',
  'audio/voice/te/your-turn.mp3'
];
// END GENERATED

var CACHE_PREFIX = 'footprint-chess-';
var CACHE = CACHE_PREFIX + VERSION;

self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(CACHE).then(function (cache) {
      return cache.addAll(FILES.map(function (f) { return new Request(f, { cache: 'no-cache' }); }));
    }).then(function () {
      return self.skipWaiting();
    })
  );
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) {
        return k.indexOf(CACHE_PREFIX) === 0 && k !== CACHE;
      }).map(function (k) { return caches.delete(k); }));
    }).then(function () {
      return self.clients.claim();
    })
  );
});

self.addEventListener('fetch', function (event) {
  var req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.open(CACHE).then(function (cache) {
      return cache.match(req, { ignoreSearch: true }).then(function (hit) {
        if (hit) return hit;
        return fetch(req).catch(function (err) {
          if (req.mode === 'navigate') {
            return cache.match('index.html').then(function (page) {
              if (page) return page;
              throw err;
            });
          }
          throw err;
        });
      });
    })
  );
});
