#!/usr/bin/env node
'use strict';

/*
 * Footprint Chess: rebuild the offline file list in sw.js.
 *
 * Node-only dev tool, no npm dependencies. The service worker (sw.js) keeps
 * every file the app needs in one cache per version, so the app works with
 * no internet after the first visit. Its file list and version live between
 * the BEGIN GENERATED / END GENERATED lines of sw.js, and this tool rewrites
 * them:
 *   - the pages (index.html, help.html, check.html) and the site root "./",
 *   - every css/*.css and js/*.js file,
 *   - every voice clip listed in js/voice-clips.js (the only clips the app
 *     ever fetches).
 * The version is a hash of every listed file's path and content, so any
 * change to any file makes a new version. The browser notices the changed
 * sw.js, fills a new cache, then deletes the old one.
 *
 * Run after any change to a page, style, script or clip (tests/offline.test.js
 * fails until you do):
 *   node tools/make-offline.js           rewrite sw.js
 *   node tools/make-offline.js --check   exit 1 if sw.js is out of date
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const SW = path.join(ROOT, 'sw.js');
const BEGIN = '// BEGIN GENERATED by tools/make-offline.js (do not edit by hand)';
const END = '// END GENERATED';

function listDir(dir, ext) {
  return fs.readdirSync(path.join(ROOT, dir))
    .filter(f => f.endsWith(ext))
    .sort()
    .map(f => dir + '/' + f);
}

/* The files the service worker keeps, in a stable order (root-relative). */
function offlineFiles(root) {
  root = root || ROOT;
  const clips = require(path.join(root, 'js', 'voice-clips.js'));
  const files = ['index.html', 'help.html', 'check.html']
    .concat(listDir('css', '.css'), listDir('js', '.js'));
  Object.keys(clips).sort().forEach(lang => {
    clips[lang].slice().sort().forEach(id => files.push('audio/voice/' + lang + '/' + id + '.mp3'));
  });
  return files;
}

function versionOf(files, root) {
  root = root || ROOT;
  const hash = crypto.createHash('sha256');
  files.forEach(f => {
    hash.update(f + '\n');
    hash.update(fs.readFileSync(path.join(root, f)));
  });
  return hash.digest('hex').slice(0, 12);
}

function generatedBlock(root) {
  const files = offlineFiles(root);
  const lines = [BEGIN, "var VERSION = '" + versionOf(files, root) + "';", 'var FILES = ['];
  const all = ['./'].concat(files);
  all.forEach((f, i) => lines.push("  '" + f + "'" + (i < all.length - 1 ? ',' : '')));
  lines.push('];', END);
  return lines.join('\n');
}

/* sw.js with its generated block replaced. */
function rebuild(swText, root) {
  const start = swText.indexOf(BEGIN);
  const end = swText.indexOf(END);
  if (start === -1 || end === -1 || end < start) throw new Error('sw.js has no generated block');
  return swText.slice(0, start) + generatedBlock(root) + swText.slice(end + END.length);
}

function main() {
  const current = fs.readFileSync(SW, 'utf8');
  const next = rebuild(current);
  if (process.argv.includes('--check')) {
    if (next !== current) {
      console.error('sw.js is out of date: run node tools/make-offline.js');
      process.exit(1);
    }
    console.log('sw.js is up to date');
    return;
  }
  if (next !== current) fs.writeFileSync(SW, next);
  console.log('sw.js: ' + (next === current ? 'unchanged' : 'updated') + ' (' + offlineFiles().length + ' files)');
}

module.exports = { offlineFiles, versionOf, generatedBlock, rebuild, BEGIN, END };

if (require.main === module) main();
